### ISSUE TITLE
V3 Plan

### ISSUE THREAD

**Issue by CharleeWa** [easy-temps/vue3-vant-mobile#84]
#### 重构

- [ ] 整体布局优化
- [ ] 目录结构优化
- [ ] 移除弃用包

#### 新增演示组件

- [ ] 长列表加载
- [ ] 登录&注册
- [ ] 忘记密码
- [ ] 个人中心
- [ ] 我的设置

**Comment by shilohooo** [comment]
加油 👍

**Comment by sniper19891112** [comment]
Hello
I have download https://github.com/easy-temps/vue3-vant-mobile and ran it
but I got the following error
ReferenceError: definePage is not defined
    at setup (index.vue:5:1)
ReferenceError: isDark is not defined
    at setup (App.vue:7:1)

maybe don't load auto-imports.d.ts file

could you help me, please?

**Comment by sniper19891112** [comment]
I have solved that issue.
Thanks

**Comment by CharleeWa** [comment]
V3 所有功能开发完毕 🎉🎉🎉
